theme = "dracula_light"

[editor]
true-color = true

[keys.normal]
"^" = "goto_first_nonwhitespace"
"$" = "goto_line_end"

C-h = "jump_view_left"
C-j = "jump_view_down"
C-k = "jump_view_up"
C-l = "jump_view_right"

[keys.select]
"^" = "goto_first_nonwhitespace"
"$" = "goto_line_end"
